FROM antimodes201/steamcmd-base:build
MAINTAINER antimodes201

# Set some Variables
ARG GAME_PORT=27000
ARG QUERY_PORT=27003
ARG STEAM_QUERY=27020
ARG STEAM_PORT=27021
ARG RCON_PORT=27015


ENV BRANCH "public"
ENV INSTANCE_NAME "default"
ENV GAME_PORT $GAME_PORT
ENV QUERY_PORT $QUERY_PORT
ENV STEAM_PORT $STEAM_PORT
ENV STEAM_QUERY $STEAM_QUERY
ENV RCON_PORT $RCON_PORT
ENV ADDITIONAL_ARGS ""
ENV ADMIN ""
ENV TZ "America/New_York"


ADD start.sh /scripts/start.sh

# Expose some port
EXPOSE $GAME_PORT/udp
EXPOSE $GAME_PORT/tcp
EXPOSE $QUERY_PORT/udp
EXPOSE $STEAM_PORT/udp
EXPOSE $STEAM_QUERY/udp
EXPOSE $RCON_PORT/tcp

CMD ["/scripts/start.sh"]

